# Generated by Django 4.1.5 on 2023-04-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="ftp",
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="sample",
            name="gwips",
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="sample",
            name="ribocrypt",
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="sample",
            name="trips",
            field=models.CharField(default=False, max_length=200),
        ),
    ]
