# Generated by Django 4.2.30 on 2026-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gwips",
            name="BioProject",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ribocrypt",
            name="BioProject",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="ribocrypt",
            name="Run",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="sample",
            name="Run",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="trips",
            name="BioProject",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="trips",
            name="Run",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
