# Generated by Django 4.2 on 2024-09-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="study",
            old_name="Organism",
            new_name="ScientificName",
        ),
        migrations.AlterField(
            model_name="trips",
            name="Trips_id",
            field=models.CharField(max_length=100),
        ),
    ]
