# Generated by Django 4.2 on 2023-06-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='MicroRNA',
            new_name='microRNA',
        ),
    ]
