# Generated by Django 4.1.5 on 2023-04-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0002_alter_sample_ftp_alter_sample_gwips_and_more")]

    operations = [migrations.RemoveField(model_name="sample", name="Custom_columns")]
