# Generated by Django 4.2 on 2023-10-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ribocrypt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ribocrypt',
            old_name='run',
            new_name='Run',
        ),
    ]
