# Generated by Django 4.1.5 on 2023-04-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0003_remove_sample_custom_columns")]

    operations = [
        migrations.RenameField(
            model_name="sample", old_name="riboseq", new_name="study"
        )
    ]
