# Generated by Django 4.2 on 2023-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gwips_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='gwips_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='readfile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ribocrypt_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='trips_id',
            field=models.BooleanField(default=False),
        ),
    ]
