# Generated by Django 4.1.5 on 2023-04-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0004_rename_riboseq_sample_study")]

    operations = [
        migrations.RenameField(
            model_name="sample", old_name="Study_Accesion", new_name="Study_Accession"
        )
    ]
