# Generated by Django 4.1.5 on 2023-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0005_rename_study_accesion_sample_study_accession")]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="ftp",
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="sample",
            name="gwips",
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="sample",
            name="ribocrypt",
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="sample",
            name="trips",
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="sample",
            name="verified",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
