# Generated by Django 4.1.5 on 2023-04-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0006_alter_sample_ftp_alter_sample_gwips_and_more")]

    operations = [migrations.RemoveField(model_name="sample", name="study")]
