# Generated by Django 4.1.5 on 2023-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0007_remove_sample_study")]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="avgLength",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="bases",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="size_MB",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="spots",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
