# Generated by Django 4.1.5 on 2023-04-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0008_alter_sample_avglength_alter_sample_bases_and_more")]

    operations = [
        migrations.RenameField(
            model_name="study", old_name="Acession", new_name="Accession"
        )
    ]
