# Generated by Django 4.1.5 on 2023-04-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0009_rename_acession_study_accession")]

    operations = [
        migrations.RenameField(
            model_name="study", old_name="GSE_Supplementary", new_name="Name"
        )
    ]
